### docker-compose file for demo environment
# Usage:
# docker-compose -f ./examples/docker-compose.yml --project-directory . -p camunda-db up

version: "3.7"
services:

  camunda-db:
    image: postgres
    volumes:
      - camunda-db-vol:/var/lib/postgresql
    networks:
      - mynet
    environment:
      - TZ=Europe/Zurich
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Initial@Password
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    hostname: camunda-db

  create-dbs-camunda:
    image: boxfuse/flyway
    networks:
      - mynet
    volumes:
      - ./create-dbs-camunda:/flyway/sql
    command: migrate -url=jdbc:postgresql://camunda-db:5432/postgres -user=postgres -password=Initial@Password -schemas=create-dbs -connectRetries=10
    depends_on:
      - camunda-db

  camunda:
    image: camundala-starter:latest
    networks:
      - mynet
    #volumes:
    # if you need to customize bpm-platform.xml
    # - ./install/camunda/7.10.0/bpm-platform.xml:/camunda/conf/bpm-platform.xml
    environment:
      TZ: "Europe/Zurich"
      HOST_PORT: 8085
      DB_DRIVER: "org.postgresql.Driver"
      DB_URL: "jdbc:postgresql://camunda-db:5432/camunda"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Initial@Password"
      DB_TEST_ON_BORROW: "true"
      ADMIN_USERNAME: "kermit"
      ADMIN_PASSWORD: "kermit"
      ADMIN_FIRSTNAME: "Kermit"
      ADMIN_LASTNAME: "The Frog"
      ADMIN_EMAIL: "kermit@pme123.com"
      WAIT_FOR: "camunda-db:5432"
    ports:
      - "8085:8085"
    hostname: camunda
    depends_on:
      - camunda-db
      - create-dbs-camunda

volumes:
  camunda-db-vol:

networks:
  mynet:
